### ISSUE TITLE
My shortcut to move app to other screen centered stopped working after latest update.

### ISSUE THREAD

**Issue by pentago** [rxhanson/RectanglePro-Community#100]
I had a shortcut CTRL+OPTION+CMD+ARROW LEFT/RIGHT to move apps on next/previous screen centered which worked fine until latest update, now it doesn't. How do I figure out why?

Did anything changed in reards to shortcuts, perhaps some new sort of conflict?

**Comment by rxhanson** [comment]
Thanks for reporting. Indeed, I did break this. I'll be pushing out a follow on release real soon with a fix. It has to do with the addition of next/prev display that preserves ratio.

**Comment by rxhanson** [comment]
Ok, v2.5.1 has the fix for this and can be updated from within the app or at https://rectangleapp.com/pro. Let me know if you still have any issues here.

**Comment by pentago** [comment]
All working well now, thanks for amazing speedy resolution <3

**Comment by pentago** [comment]
Great, thanks!
