### ISSUE TITLE
Flotato apps don't appear in New App Shortcut list

### ISSUE THREAD

**Issue by jschuur** [rxhanson/RectanglePro-Community#114]
I use [Flotato](https://www.flotato.com/) to create standalone apps for certain web pages, and noticed that these don't appear in the list when creating app layouts. They each have their own entry in /Applications (although looking at the Activity Monitor, the process is just 'Flotato' and not the app name in /Applications.

Curiously, there is an entry for Flotato, but it has the icon of one of my Flotato apps (Netflix). So it looks like it's treating them all as just one app somehow. I thought maybe the apps were symlinks, but that doesn't seem to be the case either.

It would be nice to be able to just drag an app into an Applications group to identify it.

**Comment by rxhanson** [comment]
Sorry for the delay on this one. Adding support for Flotato would likely be a decent amount of (one-off) effort, and something I can only justify with significant user demand. 

> It would be nice to be able to just drag an app into an Applications group to identify it.

This makes sense to me. I'll add this to my backlog to work when I'm back in that part of the code.

**Comment by jschuur** [comment]
Understood. To be fair, I don't use app shortcuts anyway without macOS support to target specific desktops, so it's not an issue.

Happy with Rectangle Pro otherwise :)
