### ISSUE TITLE
an issue with Obsidian

### ISSUE THREAD

**Issue by Korean-David** [rxhanson/RectanglePro-Community#115]
After the recent update, I'm having an issue with Obsidian. 
So often, I had to trigger a window throw _twice_ to move Obsidian's windows. 
So can you please look into this?

**Comment by rxhanson** [comment]
I should have a new build out in the next few days or so that will bring the necessary underlying parts of the window throw back to what they were prior to v2.5.

In the meantime, you can downgrade to v2.4.7 at https://rectangleapp.com/pro/versions if desired.
