### ISSUE TITLE
"Activate" Hotkey + Key(s)

### ISSUE THREAD

**Issue by panckreous** [rxhanson/RectanglePro-Community#117]
Inspired by #113, and [I think] distinct enough to merit its own issue as you said you prefer:

I'd love if, in addition to global hotkeys, there was some sort of Activate hotkey that, followed by one or more keys, would trigger whatever action it was assigned to. 

This would allow for lesser-used actions to also be accessible via hotkey, without cluttering the global hotkey space (Although, if this existed, I'd use it for a lot of my actively-used hotkeys too)

So, for example:

- Say I don't have "first third" assigned since I don't use it enough to merit another global hotkey. Where the current UI lets me record a hotkey, there's now a checkbox after the input to make it an internal shortcut instead. In the record hotkey input I press f and then t, then check that new imaginary checkbox. 

- Now, from anywhere, I press my global Activate hotkey (which I set in the main preferences pane), then f, then t, and "first third" is triggered. Or I just make the key a single "t" or whatever it may be. The shortcuts I use the most continue to work as they are since I only toggled that new checkbox in this case. 

- If I press the Activate hotkey, followed by nothing after a second or whatever it is, nothing happens. Down the line there could be an option I toggle so when I hit the Activate hotkey it shows an overlay of all the shortcuts I have set up in case they're not all memorized, etc

thank you sir

**Comment by rxhanson** [comment]
Thanks for rolling this into its own issue. Right now I'm working on some menu stuff that might make this unnecessary?

Here's what's going in the next release for this feature, hopefully out in a few days:
1. Provide the ability to curate the menu bar menu, with the ability to add custom shortcuts/application shortcuts.
2. Show the menu (with only the window actions, not the prefs window menu item, etc) like a context menu using either a keyboard shortcut, or specified mod keys + left click. 

For shortcuts that aren't commonly used, visual selection from a menu would be my desired path. As always, it would take some playing around with it to see what's best.

**Comment by mickimnet** [comment]
> 1. Provide the ability to curate the menu bar menu, with the ability to add custom shortcuts/application shortcuts.
> 2. Show the menu (with only the window actions, not the prefs window menu item, etc) like a context menu using either a keyboard shortcut, or specified mod keys + left click.

I love that idea! That would mean, that I could omit menu entries, where I already have keyboard shortcuts defined and memorized, and focus on the functions I seldom or rarely use.

Also being able to open the menu like a context menu with a hotkey *and* being able to use the menu with the keyboard, would give me the option to use more functionalities of Rectangle, without the need for more keyboard shortcuts.

That would solve the need from #113 for me.

**Comment by panckreous** [comment]
@rxhanson you can close this now if you feel so inclined. I just saw you added rectangle-pro:// which covers this use case (and is overall amazing, thank you for adding that)
