### ISSUE TITLE
Can't get `Left Half` to stay set in snap areas

### ISSUE THREAD

**Issue by RyanRoberts** [rxhanson/RectanglePro-Community#125]
Here's a video of what's happening https://media.yep.digital/XV5zz5

So strange.

**Comment by rxhanson** [comment]
Thanks! I checked in a fix that will go into the next build. Functionally, it still worked properly for me despite not displaying correctly. (I think this is a really minor macOS bug related to using the value 0 as an ID for a menu item - the ID for left half in this case).

**Comment by rxhanson** [comment]
(Housekeeping)
