### ISSUE TITLE
Preference window->Menu & Icon section: resizing the window doesn't resize the listview

### ISSUE THREAD

**Issue by mickimnet** [rxhanson/RectanglePro-Community#141]
Hello everybody,

I just installed version 2.6.3 (125) on macOS Monterey 12.6, and wanted to use the _"ability to configure which commands are available in the menu bar menu"_ feature--for the first time.

As I have a big display, I like to use the full height of my display for long lists (like _Keyboard Shortcuts_ or _Custom Shortcuts_), but when I height maximize the _Menu & Icon_ section, the listview of the menu doesn't size acordingly. It actually does, after I switched to the before mentioned other two menu entries, I like to height maximize. See pictures, below (beware, they are quit long!).
 
<img width="981" alt="RectanglePro-Preferences-Menu+Icon-default size" src="https://user-images.githubusercontent.com/2911922/196042411-f4b8b88b-bf61-4bd4-9158-cb7a7c517cda.png">
<img width="981" alt="RectanglePro-Preferences-Menu+Icon-initial height maximized" src="https://user-images.githubusercontent.com/2911922/196042439-2afc461c-2f45-439a-863c-5798b06c4e67.png">
<img width="981" alt="RectanglePro-Preferences-Menu+Icon-after switching back and forth" src="https://user-images.githubusercontent.com/2911922/196042467-59c128c5-271c-42d1-913e-882fb87b6658.png">

**Comment by mickimnet** [comment]
**Related to the above issue**: after I switched back and forth (in the third picture above), I cannot scorll in the listview. If I have multiple items extended and switch back and forth again, I can scroll in the listview.

**Comment by rxhanson** [comment]
Thanks for reporting this one, too. I'll also fix this one in the next release.

**Comment by mickimnet** [comment]
This problem persists in version 2.7 (126).
