### ISSUE TITLE
Preference window->Menu & Icon section: cannot deselect sub-entries

### ISSUE THREAD

**Issue by mickimnet** [rxhanson/RectanglePro-Community#142]
Hello everybody,

As I would like to keep only entries in the menu of _RectanglePro_--version 2.6.3 (125) on macOS Monterey 12.6--, where I don't have shortcuts for (yet😎), I tried to deselect submenu entries, but it didn't work. See pictures, below.

<img width="250" alt="RectanglePro-Preferences-Menu+Icon-no deselecting submenu items-menu" src="https://user-images.githubusercontent.com/2911922/196044050-21304968-44ba-4997-803d-2133c70fff86.png">
<img width="981" alt="RectanglePro-Preferences-Menu+Icon-no deselecting submenu items-preferences" src="https://user-images.githubusercontent.com/2911922/196043584-1c8a0521-c075-49db-863a-d543706f41ed.png">

**Comment by rxhanson** [comment]
Thanks for reporting. I'll patch this one up in the next release.

**Comment by mickimnet** [comment]
Works now! Thank you very much!
