### ISSUE TITLE
applyGapsToMaximize and applyGapsToMaximizeHeight not working in Pro

### ISSUE THREAD

**Issue by SeanMcLoughlin** [rxhanson/RectanglePro-Community#149]
I am on version 2.6.3.

I tried the following commands in Rectangle Pro, quit and restarted Rectangle Pro, and the feature does not work (i.e. Maximize and Maximize Height still make gaps). I did the equivalent in Rectangle (non-pro) and it works as intended.

```
defaults write com.knollsoft.Hookshot applyGapsToMaximize -int 2
defaults write com.knollsoft.Hookshot applyGapsToMaximizeHeight -int 2
```

I can try and provide a recording if this is not reproducible.

**Comment by rxhanson** [comment]
Looks like I never carried that over to Pro. I'll slate this for the next release.

**Comment by rxhanson** [comment]
Here you go: https://rectangleapp.com/pro/downloads/Rectangle%20Pro%202.7.2.dmg
