### ISSUE TITLE
Cascade windows window size too small

### ISSUE THREAD

**Issue by lipasti** [rxhanson/RectanglePro-Community#15]
Cascade windows function leaves the windows too small, unusably small in my opinion. Can this be configured somehow? 

Preferably the function would calculate the window size based on how many windows are being cascaded. More windows -> more space needed for cascading -> less space for the windows themselves. Less windows -> less space needed for cascading -> more space for the windows themselves.

**Comment by rxhanson** [comment]
At the very least, I'll add in way to adjust the window size via terminal command in the next release. I'll put dynamic size calculations on my backlog and see where it makes sense to fit that in.

**Comment by lipasti** [comment]
Thanks Ryan, a terminal command to adjust configuration is a very good
workaround for me.

**Comment by rxhanson** [comment]
Added in 2.2.2 (https://rectangleapp.com/pro/versions)

defaults write com.knollsoft.Hookshot cascadeWidth -int <PIXELS>
defaults write com.knollsoft.Hookshot cascadeHeight -int <PIXELS>

(<PIXELS> being your defined size)

Then restart the app.

Let me know if you have any issues.

**Comment by JangPooH** [comment]
@rxhanson 
Thanks for letting me know about the option to adjust cascade window size.
The default option seems 1/4 size of available window, so I think relative value(like 70%) can be used as cascadeWith and Height, but I don't know find how to set it.
Is there other cascade window size options can I use instead of fixed int type?

**Comment by rxhanson** [comment]
This Terminal command will make the cascade take up the display.
```
defaults write com.knollsoft.Hookshot cascadeVersion -int 2
```
Restart the app after executing.
