### ISSUE TITLE
all functions stopped working in 13.2 beta 2

### ISSUE THREAD

**Issue by avincent98144** [rxhanson/RectanglePro-Community#167]
all functions of paid pro stopped working in 13.2 beta 2. even tho the settings are intact from beta 1, nothing is snapping to my configs. 

did a full delete and re-install .. same issue. 

it is not crashing so no reports to add.

**Comment by rxhanson** [comment]
Sounds like accessibility permission handling macOS side might be shaky in that beta. I would expect it to be fixed in a subsequent macOS beta. You could try quitting the app, disabling it in the Accessibility system prefs, removing it in the Accessibility system prefs, and re-adding it.

**Comment by avincent98144** [comment]
yes, I did exactly that

**Comment by avincent98144** [comment]
A new discovery.  My firewall flagged this GOOGLE connection. Not sure why it appears twice.

We are a strict no google lab and I’m curious why your app is connecting to an unrelated service.

Looking forward to your reply.

Cheers
Anthony Vincent

￼

￼

**Comment by rxhanson** [comment]
Rectangle Pro is capable of 2 outward requests. 

1. Paddle license verification - to Paddle servers.
2. Checking for updates (if enabled or triggered manually) - to rectangleapp.com.

If the Paddle verification is blocked, it will try again.
Rectangleapp.com is hosted via Google App Engine, so it's possible that this connection could be marked as Google.

I take privacy seriously and don't do anything with any user data. I don't opt in to additional update information and I don't opt in to additional Paddle information.

**Comment by avincent98144** [comment]
Thanks for quick comeback.  I am 100% comfortable w/ all PADDLE connections except anything telemetry, which is globally blocked anyway.

The GOOGLE connection is also a global rule with exceptions to the rare FIREBASE solution.

Your app does not appear to be hindered with the GOOGLE block and appreciate your explanation.

A manual update trigger connected and confirmed the app is current.

Cheers
Anthony Vincent

**Comment by panckreous** [comment]
In case this wasnt resolved, I experienced something similar recently. In case this helps: 

- back up current prefs
- completely uninstall rectangle pro using app cleaner, restart
- go into system settings/preferences -> privacy -> accessibility, uncheck rectangle pro, authenticate, quit system settings, restart
- go back into system settings/preferences -> privacy -> accessibility, highlight rectangle pro, click the little hard-to-see minus to remove it from the list, restart
- fresh install, restore prefs and license

Are all the quits and restarts necessary? Not sure, but between Ventura and Mojave and all its alpha-ness in so many places... probably.

**Comment by rxhanson** [comment]
Thanks, I'm going to build out an FAQ of sorts for common issues like this since the latest releases of macOS have been causing this type of issue more frequently than usual. This is what I've been recommending:

1. Quit Rectangle Pro
2. In System Settings > Privacy & Security > Accessibility, first disable Rectangle Pro then remove it with the minus
3. Restart your Mac, then re-enable Rectangle Pro

The restart here doesn't seem to always be necessary, but for some users it has.
