### ISSUE TITLE
2x2 and 2x3 tiles do not take dock into account

### ISSUE THREAD

**Issue by matlegdev** [rxhanson/RectanglePro-Community#17]
2x2 and 2x3 tiles are ignoring the dock on my 14" M1 pro, which makes the feature kind of useless (in an otherwise amazing software!). I do not see any settings that would allow me to fix this, so I'm assuming this is a bug. 

[Here is what happens if I use the `bottom left` option (dock is taken into account, works perfectly)](https://user-images.githubusercontent.com/88509983/154817132-71572de1-2404-42fc-8216-e27826766d34.png)

[Here is what happens if I use the `2x2 Tiles` option (this behavior is what I would expect if my dock was on top)](https://user-images.githubusercontent.com/88509983/154817161-f20a5d4d-d3d3-44c3-bf18-d29487c985ff.png)

**Comment by rxhanson** [comment]
Please try v2.2.2:
https://rectangleapp.com/pro/versions

**Comment by matlegdev** [comment]
Just tried it and it now works as expected. Thanks!
