### ISSUE TITLE
Bug: Resize doesn't work on several IntelliJ pop-ups

### ISSUE THREAD

**Issue by shane-tang** [rxhanson/RectanglePro-Community#173]
There are several windows in IntelliJ (eg. double-shift, command+shift+F) that can be repositioned by Rectangle/Pro but can't be resized.

They don't appear to use the standard API for windows which likely breaks this functionality, but it'd be really great to add a special case to support these windows. These windows can be resized by dragging any corner but the target area is really small, so Rectangle/Pro support would be amazing.

Steps to repro:

1. Bind a resize hotkey under Rectangle Pro > Preferences > Window Throw > Resize
![image](https://user-images.githubusercontent.com/22078613/201881983-b1973fb9-6e07-4aec-abd6-f05f88fb34bc.png)
2. Open IntelliJ (or similar forks, like Android Studio)
3. Press Command+Shift+F
4. Attempt to resize the pop-up using the hotkey + mouse
    * Using snap will also reposition the window but not resize the window

These windows are some of my most frequently-resized windows and are among the only windows I've noticed don't work with resize.

**Comment by shane-tang** [comment]
I searched this repo's issues and didn't see anything similar [but I just now noticed this similar issue on regular Rectangle.](https://github.com/rxhanson/Rectangle/issues/872) I'm guessing there's no chance of support since it doesn't use the standard accessibility API?

**Comment by rxhanson** [comment]
Right, this does come down to JetBrains IDEs not using standard windows in these situations, so they cannot be manipulated via the accessibility API. This is most commonly seen with cross-platform applications that have been around a while.
