### ISSUE TITLE
Minimum macOS version listed on website out of date

### ISSUE THREAD

**Issue by Aaron-Rumpler** [rxhanson/RectanglePro-Community#182]
The Rectangle Pro website lists macOS Sierra (10.12) as the minimum version, but for the current version (2.7.3), both the Sparkle manifest and the application's Info.plist list macOS High Sierra (10.13) as the minimum version.

**Comment by rxhanson** [comment]
Thanks! It's now updated. When Ventura rolled out, there was some ambiguity about Xcode allowing 3rd party developers to support 10.12, so I decided to up it to 10.13 for Pro. Based on what I've noticed with Rectangle, there are so few users running 10.12 that I don't think it makes sense to change it back.

**Comment by rxhanson** [comment]
By the way, @Aaron-Rumpler, thanks for your help answering things & such on the Rectangle Github repo. If you want license keys for any of my apps, just send me an email.
