### ISSUE TITLE
Save current layout doesn't remember Firefox location

### ISSUE THREAD

**Issue by brianhogg** [rxhanson/RectanglePro-Community#194]
The save current layout works great, but doesn't seem to move the Firefox window when the shortcut is used. It does list the location in Rectangle Pro when the current layout is captured, but has no effect. This is on MacOS 11.7.2 Firefox 107.0.1

**Comment by rxhanson** [comment]
Thanks for reporting. I can't reproduce this. I assume that normal commands like keyboard shortcuts for moving & resizing Firefox are still working?

It would be best to have logs: hold the option key, and in the menu bar menu select view logging. Then reproduce the issue.

**Comment by brianhogg** [comment]
No problem! I am able to use the other commands for moving & resizing the window, and after restarting Firefox it now seems to be responding to the application layout keyboard shortcut. Will close for now and re-open with a log if I'm able to reproduce again.
