### ISSUE TITLE
Drag and drop for reorder list works strange

### ISSUE THREAD

**Issue by ysBach** [rxhanson/RectanglePro-Community#196]
I wanted to reorder the list of choices by drag-and-drop, but it does not work.
I think this GIF explains better: https://recordit.co/pqZSmB3EtP
(the item that I clicked is still sticked to my cursor even after I unpressed mouse buttons)

**Comment by rxhanson** [comment]
Thanks for reporting. I'll add this to my queue for next release.

**Comment by rxhanson** [comment]
I can't actually reproduce this; the drag and drop reordering works fine for me. Do you have any apps running that might be interfering with drag and drop?

**Comment by rxhanson** [comment]
Cleaning up old issues; let me know if this is still an issue.
