### ISSUE TITLE
[Rectangle Pro] Ignored apps are not ignored by 'multiple windows' options

### ISSUE THREAD

**Issue by kxyr** [rxhanson/RectanglePro-Community#197]
- [x] This is a new bug that hasn't been documented in a closed issue or in the Readme.

macOS version: Ventura 13.1
Rectangle version: v2.7.4
Logs if applicable (In Rectangle menu, hold option, "View Logging..."): 

I configured 'Ignore app" for the Mac "Stickies" app, but when pressing `Multiple Windows -> 2x2 Tiles`, it did not allow the ignored app to retain its current position, but shifted it to the 2x2 layout. It would be great if the ignored app could be applied for all the options under `Multiple Windows` as well.

**Comment by rxhanson** [comment]
Thanks for reporting. I'll add this to my queue for the next release.
