### ISSUE TITLE
Bug/Enhancement request: Chrome "Shortcut" site-specific apps don't respond to move/resize

### ISSUE THREAD

**Issue by aharnly-amplify** [rxhanson/RectanglePro-Community#198]
Background:

Chrome allows the creation of single-site apps via a "Create Shortcut" menu item. These apps behave just like chrome, but open in a separate window to a specific URL and have their own Dock icon, app tab switcher icon, etc.

Rectangle Pro, as you know, supports keyboard shortcuts for "Move" and "Resize" actions.

The bug is that when these Chrome shortcut apps open in their own window, they do not respond to Rectangle Pro's move/resize shortcuts, although the normal click+drag resizing works. I realize this may be due to some oddity in how these apps work, but thought I'd put it on your radar in case it can be addressed.

Versions:
* macOS: macOS Monterey Version 12.5.1
* Chrome: Version 108.0.5359.124 (Official Build) (arm64)
* Rectangle Pro: Version 2.7.4 (130)

To reproduce:

1. Open Chrome
2. Navigate to a website, e.g. mail.google.com, github.com, whatever.
3. Click the triple-dot menu in the top right > More Tools > Create Shortcut
4. Choose a name (the default is probably fine), and check the "Open as Window" checkbox.
5. The app should open, with a dock icon and a separate window.
6. Attempt to use a Rectangle Pro keyboard shortcut for "Move" or "Resize"

Expected: As with Chrome itself, or other apps, the window should move or resize.
Actual: The window does not move or resize.

I've attached a short screencast demonstrating the behavior.

https://user-images.githubusercontent.com/26876682/210250452-6a4bd281-6405-497d-9076-b855760f9987.mov

**Comment by rxhanson** [comment]
Thanks for the detailed report. Indeed, this is a scenario where Chrome is creating windows that cannot be manipulated by Rectangle Pro. As far as I know, there is no way to fix this Rectangle Pro side. I'll keep this issue open and update it if I find a way around it.

**Comment by aharnly-amplify** [comment]
I'm not sure if you changed something or Chrome did, but these apps now work! I'm running Rectangle Pro 2.7.10 (136) and Chrome Version 110.0.5481.177 and all is well, though I don't recall exactly when these started working.
