### ISSUE TITLE
Be able to apply gaps *only* to screen edges (not between windows)

### ISSUE THREAD

**Issue by eramdam** [rxhanson/RectanglePro-Community#202]
What the title says, I like the window gaps option but I wish I could be able to have separate values for the gaps between windows and the gaps between windows and the edge of the screen 😄

**Comment by rxhanson** [comment]
I am planning on adding this into the UI for Pro. Until then, here are the terminal commands:

defaults write com.knollsoft.Hookshot screenEdgeGapTop -int 10
defaults write com.knollsoft.Hookshot screenEdgeGapBottom -int 10
defaults write com.knollsoft.Hookshot screenEdgeGapLeft -int 10
defaults write com.knollsoft.Hookshot screenEdgeGapRight -int 10

Restart the app after executing defaults for them to take effect.

Nearly all of the terminal commands in https://github.com/rxhanson/Rectangle/blob/master/TerminalCommands.md apply to pro, just replace `Rectangle` with `Hookshot`

**Comment by eramdam** [comment]
Amazing, thank you!!
