### ISSUE TITLE
Rectangle Pro Not compatible with MacBook Pro 2011 running 10.13.6 OS X

### ISSUE THREAD

**Issue by KellyGerling** [rxhanson/RectanglePro-Community#214]
Rectangle Pro worked fine last year. My current version is 2.7.4. It doesn't work at all. I click on the application in the Applications folder. Before, an icon showed up on top. Now, nothing happens at all.

I have a license code for the $10 version of Rectangle Pro.

I downloaded the latest version, 2.7.5. It shows that it is not compatible with my OS X or Computer:

MacBook Pro (13-inch, Late 2011)
2.8 GHz Intel Core i7
16 GB 1333 MHz DDR3
Image:

![Rectangle Pro 2 7 5 rejection as incompatible](https://user-images.githubusercontent.com/67030958/214735521-0d4d31b8-e665-4f03-a94d-827fe108def9.png)

Can I revert to a previous version of Rectangle Pro?

Or do something else?

Kelly

Kelly Patrick Gerling
kelgerling@gmail.com
Seattle

**Comment by KellyGerling** [comment]
I found another earlier version of Rectangle Pro. It is labeled version: 2.4.7 "created April 5, 2022."

It works. So that's a solution.

If there is another solution to use upgraded versions, including the current 2.7.5. I'd like to know.

Thanks!

**Comment by rxhanson** [comment]
Thanks for reporting, and for having purchased the app. Looking back at the changes, I think 2.7.2 might be the most recent one that should work on 10.13.6. (Nov 14 2022).  

https://rectangleapp.com/pro/downloads/Rectangle%20Pro%202.7.2.dmg

I think the breaking change would have been on the next build on Nov 16, 2022. You're fine sticking with 2.4.7, though.

Unfortunately, the outcome of this is that I am going to move to only officially support 10.14+ going forward. Apologies for the inconvenience. 

Here's my logic: If I move to a minimum version of 10.14, then the app isn't forced to bundle the Swift runtime which cuts the size on disk by a large amount (downloads will use a fraction of the bandwidth). In order to keep the updating library and the licensing library up to date and still support 10.13.6, I would have to replace the shortcut recorder library, which is causing the crash on launch in v2.7.4. Replacing the shortcut recorder library is not a small task. It is one that I've planned for a long time because I don't have plans to maintain it and there is a better alternative that I can personally maintain easier, but it will take some time to do it. Perhaps once I get the shortcut recorder replaced, I'll be able to extend support back to 10.13.6 if there is enough demand. You're the first to report this and it's been over 2 months since the app didn't work on 10.13.6.

**Comment by KellyGerling** [comment]
Thanks Ryan. It so happens that neither 2.7.4 or 2.7.5 will work. But the older version I mentioned — 2.4.7 — still worked fine. I just happened to have it in the Application Folder of my backup hard drive. That will work perfectly for my purposes. However, I’ll try 2.7.2. Thanks for this link:rectangleapp.comThanks so much. It’s a brilliant app. I think you need to optimize for the majority of users, most of whom use more recent OS Xs and newer Mac hardware. My one suggestion is to make a prominent, easy-to-see part of your website that links to legacy versions. I simply missed seeing it if is indeed there. Thanks. I love the cascade feature. KellySent from my iPhoneKelly Patrick GerlingPhone:Cell: ***@***.*** Jan 25, 2023, at 6:14 PM, Ryan Hanson ***@***.***> wrote:﻿
Thanks for reporting, and for having purchased the app. Looking back at the changes, I think 2.7.2 might be the most recent one that should work on 10.13.6. (Nov 14 2022).
https://rectangleapp.com/pro/downloads/Rectangle%20Pro%202.7.2.dmg
I think the breaking change would have been on the next build on Nov 16, 2022. You're fine sticking with 2.4.7, though.
Unfortunately, the outcome of this is that I am going to move to only officially support 10.14+ going forward. Apologies for the inconvenience.
Here's my logic: If I move to a minimum version of 10.14, then the app isn't forced to bundle the Swift runtime which cuts the size on disk by a large amount (downloads will use a fraction of the bandwidth). In order to keep the updating library and the licensing library up to date and still support 10.13.6, I would have to replace the shortcut recorder library, which is causing the crash on launch in v2.7.4. Replacing the shortcut recorder library is not a small task. It is one that I've planned for a long time because I don't have plans to maintain it and there is a better alternative that I can personally maintain easier, but it will take some time to do it. Perhaps once I get the shortcut recorder replaced, I'll be able to extend support back to 10.13.6 if there is enough demand. You're the first to report this and it's been over 2 months since the app didn't work on 10.13.6.

**Comment by rxhanson** [comment]
> My one suggestion is to make a prominent, easy-to-see part of your website that links to legacy versions. I simply missed seeing it if is indeed there.

Excellent point; I will add that to the site. Thanks!

**Comment by KellyGerling** [comment]
I tried installing 2.7.2

It worked fine. I've archived the earlier version called 7.4.7 just in
case.

Thanks so much!

And I'll keep an eye out for your website update showing legacy versions.








*Kelly Patrick GerlingPhone Number:Cell:
206-618-2888Email: ***@***.*** ***@***.***>*

**Comment by KellyGerling** [comment]
Ryan, thank you for sending me the solution — version 2.7.2 That works fine on my High Sierra OS X 10.13.6

**Comment by rxhanson** [comment]
Great, thanks for letting me know. I've updated the website & the versions page to include a download link for 2.7.2.

**Comment by KellyGerling** [comment]
Found the versions link. Very good. Thank you. I love Rectangle Pro!Sent from my iPhoneKelly Patrick GerlingPhone:Cell: ***@***.*** Jan 29, 2023, at 6:23 PM, Ryan Hanson ***@***.***> wrote:﻿
Great, thanks for letting me know. I've updated the website & the versions page to include a download link for 2.7.2.

**Comment by KellyGerling** [comment]
Hi Ryan,

My version of Rectangle v2.7.2 works perfectly. I use it to cascade my apps
windows to remove clutter. It is VERY useful for me.

*But somehow my v2.7.2, no matter what I name it, is being updated
automatically to v 2.7.4 which doesn't work on my older Mac OS.*

I don't know how to find Rectangle preferences or other potential places to
turn off automatic updates that aren't compatible with my Mac OS High
Sierra 10.13.6.

For more details about my computer see:

[image: Screen Shot 2023-03-14 at 2.24.02 PM.png]

If you have ideas for how to fix this, please share.

Our previous correspondence is included below.

Thanks Ryan!

Kelly










*Kelly Patrick GerlingPhone Number:Cell:
206-618-2888Email: ***@***.*** ***@***.***>*

**Comment by rxhanson** [comment]
Here's the setting for it:
![image](https://user-images.githubusercontent.com/13651296/225183342-64fb7af5-8e81-4fec-8a17-2c12a86455d3.png)

Let me know if something's not working right

**Comment by KellyGerling** [comment]
Perfect. Turned Automatic Updates off. Thank you Ryan!









*Kelly Patrick GerlingPhone Number:Cell:
206-618-2888Email: ***@***.*** ***@***.***>*
