### ISSUE TITLE
Cannot change shortcut to trigger an app layout.

### ISSUE THREAD

**Issue by CrescentMadeJr** [rxhanson/RectanglePro-Community#254]
Rectangle Pro: 2.8
MacOS 13.2.1

When I set a trigger to set the app layout on a monitor I am not able to change it unless I restart the app.
I set the shortcut as Ctrl+Cmd+Home.

**Comment by rxhanson** [comment]
Thanks! I'll also slate this one for this release.

**Comment by rxhanson** [comment]
This one should be fixed in v3.0+. Please reopen if it's not.
