### ISSUE TITLE
Window does not restore to original size when dragging away from the right side of the screen

### ISSUE THREAD

**Issue by geegeeman77** [rxhanson/RectanglePro-Community#257]
Rectangle Pro: 3.0
macOS 13.3.1

After snapping a window to the right side of the screen (to fill the right half), when dragging the window away, the window does not restore back to its original size. Instead, it resizes only to the border of the right side of the screen.

https://user-images.githubusercontent.com/4400903/231610634-991d11a0-3885-45d5-bf93-cd0b79752489.mp4

**Comment by rxhanson** [comment]
Thanks! I'll slate this for the next release.

**Comment by geegeeman77** [comment]
Of course! Thank you for all your hard work. I also neglected to mention that there is a similar behavior when dragging away from the "Bottom Right" and "Bottom Left." It cuts off at the bottom border of the screen.

**Comment by rxhanson** [comment]
I did some investigation into this, and I think there might not be anything I can do about it. It's a macOS limitation where Rectangle/Pro says "give this window this size", and macOS forces the dragged window's size to only extend to the edge of the display. If I can think of a workaround, I'll post back here.
