### ISSUE TITLE
Constantly crashed on preferences

### ISSUE THREAD

**Issue by marcelliino** [rxhanson/RectanglePro-Community#26]
Hi, I'm a big fan of Rectangle and recently wanted to buy RectPro (because it's more powerful).
Just today I downloaded and used the trial (for consideration), and apparently it always crashes when I want to setup all the shortcut keys.

My changes aren't reset, but they're pretty unusable as it crashes very quickly after just viewing or changing some settings (e.g. reticle colour,  keyboard / custom shortcuts). Any help or update?

What I've done:
- Closed all windows management apps (Rectangle and Magnet)
- Update the app (as prompted)
- Tried to open it with Rosetta (because I'm using M1 Mac mini)
- Checked the *Ignore "Rectangle Pro" window* button
- Re-launch the app
- Log out and Restart

All of those did not resolve the issue

I'm using  M1 Mac mini with 8GB ram on macOS Monterey 12.2.1

**Comment by rxhanson** [comment]
Thanks for trying it out and reporting. Can you send a crash report to me? You should find it in Console.app. You can email it to support@rectangleapp.com

**Comment by marcelliino** [comment]
I just sent the email, it's a zip file with 13 crash reports. Thanks for the response!

**Comment by rxhanson** [comment]
This should now be resolved in v2.3. If anyone else experiences a crash, please email crash reports directly to me.
