### ISSUE TITLE
Reflow Pin shortcut not working at startup unless config is reloaded

### ISSUE THREAD

**Issue by Gsinti** [rxhanson/RectanglePro-Community#277]
Hi,

I'm having a strange issue where sometimes the "Reflow Pin" shortcut doesn't work unless I export and then re-import my config.

Here is my config for this setting:

![image](https://github.com/rxhanson/RectanglePro-Community/assets/3287899/d1be21cf-fa55-4dd1-a60d-4cbd9b7d13c8)

I don't use pin mode actively, as I prefer to keep the screen real estate untouched, but I enjoy the reflow aspect to make a particular app pop up when needed.

I can't reliably replicate it, but I've noticed at times the reflow shortcut stops responding until I export and re-import the config.

Thanks for looking.

**Comment by rxhanson** [comment]
Thanks for reporting. I'll slate this one for the next release.

**Comment by Gsinti** [comment]
@rxhanson: Hey, sorry to bug. Pinging to get an update; any progress on this?

Thanks! :)

**Comment by rxhanson** [comment]
Not yet, sorry. It's still on my radar, though!

**Comment by rxhanson** [comment]
Ok, I finally got a chance to check this out. Fixing the bug correctly here would actually be to make the reflow not work when you don't have pin mode enabled.

The supported way to get what you're looking for is to just make an app layout with only textedit in it and check the box for `Bring windows to front`

![image](https://github.com/rxhanson/RectanglePro-Community/assets/13651296/028350bc-d5d0-47c6-a58d-07269f55e5c7)

Let me know if that's not what you're looking for.

**Comment by Gsinti** [comment]
Hey sorry, just seeing this now! Must have missed the GitHub notification.

An app layout with this option for just TextEdit works for my purposes.

Thank you!
