### ISSUE TITLE
Custom Shortcuts only work on 1 size display

### ISSUE THREAD

**Issue by addisonjames** [rxhanson/RectanglePro-Community#278]
macOS version: 13.3.1 (a) 
Rectangle version: 3.0.2 (143)

I have some Custom Shortcuts set up for custom window sizes. I set them up on my external display, but when I'm not using the display and only using my laptop, they don't work.

I think I understand why- but is there a way to fix this?

Some ideas:
- Set shortcut based on monitor resolution
- Set size as a percentage that would adapt to any size screen

Any tips or ways to fix this?

Thanks!

**Comment by rxhanson** [comment]
You can change those to values less than 1 (either decimal or fraction) to get screen percentage. In a future update, I will have an option to automatically convert them over.

**Comment by addisonjames** [comment]
This works wonderfully! Just had to guess at the values a bit. Thank you!!! 

<img width="414" alt="CleanShot 2023-05-22 at 12 57 28@2x" src="https://github.com/rxhanson/RectanglePro-Community/assets/4740129/ca159e5b-ed1c-4d89-b03e-5a95df460f16">
