### ISSUE TITLE
Stash for app assigned for All Desktops

### ISSUE THREAD

**Issue by rinodrops** [rxhanson/RectanglePro-Community#298]
- [ ] This is a new bug that hasn't been documented in a closed issue or in the Readme.

macOS version: macOS 14.0
Rectangle version: Pro v3.0.2 (143)
Logs if applicable (In Rectangle menu, hold option, "View Logging..."): 

The idea of Stash is letting an app always sits on the desktop to access it easily
but does not affect the currently used app.
I want to use ForkLift while using the other apps, so I assign ForkLift to All Desktops
using `Dock | Options` and stash it. However, the window is stashed only in one space,
even if the app itself is assigned to All Desktops.

**Comment by alexanderblackh** [comment]
Any update on this? This is the only thing holding me back from using it personally. Currently using Slidepad but it's less than ideal, rather have my native windows. Maybe doing something similar to bartender and taking advantage of screen recordings??
