### ISSUE TITLE
Gap on top randomly while snapping

### ISSUE THREAD

**Issue by validatedev** [rxhanson/RectanglePro-Community#301]
Occasionally, it occurs without any apparent reason. However, I have a video to share:

https://github.com/rxhanson/RectanglePro-Community/assets/29679552/89ee3c18-e7a9-4b10-a5bc-d0d14cc63f0f

The configurations are as follows:

<img width="843" alt="Screen Shot 2023-06-25 at 02 15 30 AM" src="https://github.com/rxhanson/RectanglePro-Community/assets/29679552/2c108f83-d262-4f23-aac7-41116d66ad58">
<img width="721" alt="Screen Shot 2023-06-25 at 02 15 43 AM" src="https://github.com/rxhanson/RectanglePro-Community/assets/29679552/c10db733-d9c4-42e7-85bb-783a150cf390">
<img width="601" alt="Screen Shot 2023-06-25 at 02 15 49 AM" src="https://github.com/rxhanson/RectanglePro-Community/assets/29679552/388dc305-c8cf-402e-9ba6-62d39828ef09">

Thanks in advance.

**Comment by rxhanson** [comment]
Thanks for the detailed report. I was able to reproduce it, and will push out a release once I get a fix in.

**Comment by validatedev** [comment]
I appreciate your response and look forward to the resolution :)

**Comment by validatedev** [comment]
Seems it is fixed by 3.0.5. Thanks @rxhanson.
