### ISSUE TITLE
Stage manager recent apps area not working

### ISSUE THREAD

**Issue by mariusraupach** [rxhanson/RectanglePro-Community#308]
### Description

The Rectangle Pro application is not responding to the Mac OS Stage Manager when the Stage Manager Recent Apps size is set. When attempting to use the Stage Manager to manage and switch between recent applications, Rectangle Pro does not resize correctly and ignores the recent apps area.

### Steps to Reproduce

1. Launch the Mac OS Stage Manager.
2. Set the Stage Manager Recent Apps size
3. Open multiple applications
4. Try to resize

### Expected Behaviour

Rectangle Pro does resize correctly with the offset of the recent apps area.

### Additional Information

- occurs after reinstall of OS and Rectangle Pro, before everything works correctly without further configuration

### Environment

- macOS Ventura 13.4.1
- Rectangle Pro v3.0.2

<img width="2056" alt="Screenshot 2023-07-11 at 20 00 47" src="https://github.com/rxhanson/RectanglePro-Community/assets/108870491/71e6dd7d-5f2e-4cfa-99eb-c2c9d16345ab">

**Comment by rxhanson** [comment]
Thanks for reporting with these details. This is working properly for me, so I suspect there might be either an edge case that you're experiencing or there's something else going on. To make this much easier for me to figure out, the most helpful things are 
1. a screen recording
2. the logs (hold option key and select View Logging...)
3. your config (export from settings tab of prefs window)

**Comment by mariusraupach** [comment]
[RectangleProConfig.txt](https://github.com/rxhanson/RectanglePro-Community/files/12018122/RectangleProConfig.txt)
[Untitled.txt](https://github.com/rxhanson/RectanglePro-Community/files/12018123/Untitled.txt)

**Comment by mariusraupach** [comment]
encountered the same problem when I installed Rectangle on a virtual machine using the exact versions I mentioned in the environment description.

**Comment by mariusraupach** [comment]
After updating to version 3.0.5, the issue persists

**Comment by mariusraupach** [comment]
After updating to version 3.0.6, the issue persists

**Comment by rxhanson** [comment]
Unfortunately, I still can't reproduce this. I've loaded your config and it works properly. Is there a prior release where you know this was working for you, and I could use that to compare what's changed?

**Comment by mariusraupach** [comment]
I am quite confident that version 3.0.2 worked on my MacBook before I reset it. Therefore, I find it very strange that it is not functioning properly now.

To ensure that the problem did not originate from my end, I conducted testing on three different systems: two MacBooks and one virtual machine. Each system underwent a fresh installation of macOS before conducting the tests.

- Installed Xcode Command Line Tools.
- Installed Homebrew via curl.
- Installed rectangle-pro using Homebrew.
- Granted accessibility permissions to rectangle-pro.
- Activated stage manager.
- Checked if the recent apps area was recognised.

The bug persists across all three systems, indicating that it is not isolated to a particular environment or configuration. (Sync configuration over iCloud is deactivated)

Environment

- macOS Ventura 13.5
- Rectangle Pro v3.0.6

**Comment by rxhanson** [comment]
Any chance you could install v3.0.2 just to guarantee that it did in fact work for you?

https://rectangleapp.com/pro/versions

**Comment by mariusraupach** [comment]
I can verify that version 3.0.2 functions as intended.

**Comment by rxhanson** [comment]
Great, thanks for doing that. That alone should be enough to narrow it down. I'll see what I can do for the next release

**Comment by mariusraupach** [comment]
Great news! The issue has been resolved with the latest update, Thank you for the fix!

**Comment by jpatrolla** [comment]
Hi gang. I believe it might be on the macOS side.
Try changing the following setting to 'Do Nothing':

System Settings > Desktop & Dock > Double-click a window's title bar to **Do Nothing**

![image](https://github.com/rxhanson/Rectangle/assets/9730683/987b3465-a620-4f47-b2d7-3820c5730148)

Seems to be fixed so far for me. Hope that helps
