### ISSUE TITLE
Feature request: Ignore app should apply to Snap Panel

### ISSUE THREAD

**Issue by abey79** [rxhanson/RectanglePro-Community#314]
(Thanks for the great app!)

I'm doing UI work and use a "ruler" app (e.g [this one](https://apps.apple.com/us/app/free-ruler/id1483172210?mt=12)), which I'm moving constantly. I would like to disable Snap Panel for this app as it's meaningless and annoying, but "Ignore App" does't apply to this feature apparently. It would be great if it did (or there was another mechanism to exclude apps from Snap Panel).

**Comment by rxhanson** [comment]
Good point, I'll slate this one for the next release.

**Comment by abey79** [comment]
Awesome! 🚀

**Comment by abey79** [comment]
Thanks for getting that in the last version 🙌🏼

**Comment by Metamba** [comment]
This is a feature I will love for Rectangle pro to have. Snapping panels always interfere with my use of Dropover to move things around.

**Comment by rxhanson** [comment]
@Metamba, this did get implemented in a previous release and I should have closed out this issue. You can ignore an app in the menu bar menu and it won't show the snap panel for that app. Perhaps you're looking for something else?
