### ISSUE TITLE
Layouts for Full-screen apps?

### ISSUE THREAD

**Issue by dsimunic** [rxhanson/RectanglePro-Community#319]
Is it technically possible to save/create the layout of a split view?

<img width="187" alt="image" src="https://github.com/rxhanson/RectanglePro-Community/assets/1206234/6f665ef7-2d4f-406f-8371-986b818ef7fd">

If I click on save current layout, it doesn't seem to know about the full screens. 

If it is not possible to detect the split screen and save current apps, would it be possible to manually create a new layout for split screen that would let one choose two apps and set the position of the split (half-half, min-left, min-right, percentage). Ideally one would be able to show that layout in Rectangle menu and clicking would launch those apps and put them in split view immediately.

There's this [PDF from WWDC15](221_improving_the_full_screen_window_experience.pdf) (click will download the file), but I don't know if any of this is applicable to Rectangle's way of operation.

**Comment by rxhanson** [comment]
> Is it technically possible to save/create the layout of a split view?

Unfortunately not, but it is easy to get that app layout if you're not in the full-screened Split View.

If you position the windows how you want them, without them being in Split View, then hit save current layout, then you should get that layout in absolute pixel dimensions. You can change the absolute pixel dimensions to values less than 1 to get screen percentages. You can also check the box for "Launch closed/minimized apps" in the App Layout.

Then in the menu tab of the prefs window, you can add that app layout to the menu.

Let me know if you hit any snags.

**Comment by dsimunic** [comment]
Thanks! I'm already using the suggested layout technique, though didn't know about screen percentages.
