### ISSUE TITLE
Customize nudge amount?

### ISSUE THREAD

**Issue by NachiGithub** [rxhanson/RectanglePro-Community#327]
Hi, 

I use the nudge left/right/up/down keyboard shortcut to move windows around. Is it possible to customize the amount by which the nudge command moves a window? 

Thanks

**Comment by rxhanson** [comment]
20px is the default.

You can change it with this terminal command, followed by an app restart:

```
defaults write com.knollsoft.Hookshot nudgeDistance -float 100
```

**Comment by NachiGithub** [comment]
Wonderful. Thanks!

It'll be good to have these options listed somewhere. I looked in [terminal commands document](https://github.com/rxhanson/Rectangle/blob/master/TerminalCommands.md), but didn't see it there.

**Comment by NachiGithub** [comment]
Thanks.
