### ISSUE TITLE
Add ability to customize Window Throw window preview color

### ISSUE THREAD

**Issue by brent-bean** [rxhanson/RectanglePro-Community#329]
It would be great if the Window Throw feature allowed you to customize the color of the window preview and not just the Reticle. On a dark monitor or dark background it can be difficult to see the preview as it is currently locked to a transparent black. I think this feature would also be good to include for accessibility reasons. At the very least, being able to control the outline color would be useful, but having independent control over the outline and the shaded area would be ideal.

**Comment by rxhanson** [comment]
Thanks for the feedback. Here is the terminal command for changing the color of the background:

`defaults write com.knollsoft.Hookshot footprintColor -string "{\"red\":0,\"blue\":0.5,\"green\":0.5}"`

It comes from Rectangle (replace com.knollsoft.Rectangle with com.knollsoft.Hookshot): https://github.com/rxhanson/Rectangle/blob/master/TerminalCommands.md

There currently isn't support for adjusting the border.

I did have plans to allow configuration of colors in the UI, and make the window allow for more vibrant colors, but that typically doesn't bubble up to the top priority.

**Comment by brent-bean** [comment]
Great, the other footprint* settings are useful to know as well. Thanks @rxhanson
