### ISSUE TITLE
Limit effective desktop size for all snap areas

### ISSUE THREAD

**Issue by mojoba** [rxhanson/RectanglePro-Community#337]
I am attempting to use a 4k 42" as my display for office and gaming use. It would be useful to limit the desktop area all windows can use to a smaller potion of the screen for office use, due to the size of the display.

Is it possible to add an option or keyboard modifier which will scale and map all of the snap areas within an arbitrarily smaller area of the desktop?

**Comment by rxhanson** [comment]
At the moment, screen edge gaps are only configurable via terminal command, although I have long had plans to add this into the UI (it seems to always get pushed to the side).

```
defaults write com.knollsoft.Hookshot screenEdgeGapTop -int 10
defaults write com.knollsoft.Hookshot screenEdgeGapBottom -int 10
defaults write com.knollsoft.Hookshot screenEdgeGapLeft -int 10
defaults write com.knollsoft.Hookshot screenEdgeGapRight -int 10
```

Restart the app after executing terminal commands.
