### ISSUE TITLE
Resize adjacent windows not working all the time

### ISSUE THREAD

**Issue by mojoba** [rxhanson/RectanglePro-Community#338]
Resize adjacent windows is enabled but only works sometimes and other times it doesn't or it works inconsistently such that only the height or width of the adjacent window will resize, particularly on some desktops vs others. If I restart the app or cycle the checkmark then it resets it but the feature is still somewhat sporadic.

**Comment by rxhanson** [comment]
Thanks for reporting this. Sporadic behavior like this tends to point to scenarios outside the control of the app, and even if a workaround can be built into the app, it's typically really hard to narrow things down to a good solution. Unfortunately, I can't reproduce it. At the very least, if you can narrow it down then that would be our best chance at getting some kind of solution in place. Does it happen more with certain apps? Do you have any other apps running with Accessibility API privileges that are running at the same time?
