### ISSUE TITLE
Unable to change "Sound" output reliably while Rectangle Pro is running

### ISSUE THREAD

**Issue by matchai** [rxhanson/RectanglePro-Community#345]
Hey folks. I know this sounds like a weird one, but I've been able to pretty consistently reproduce this bug where my Sound Output or Input can't be changed while Rectangle is running, as shown in the video. It's been happening for a few weeks at this point.

https://github.com/rxhanson/RectanglePro-Community/assets/4658208/7a1d52c8-7325-4270-9e08-450e0c629b2d

Let me know if I can provide anything from my end to help. Cheers!

**Comment by rxhanson** [comment]
Thanks for reporting. This appears to be a bug introduced in macOS 13.5. Rectangle Pro needs to listen to clicks for drag to screen edge snapping to work properly, and that's what causes this issue. At the moment, I don't have a good workaround for it, so as a not-so-good workaround, you can install the latest version of Rectangle Pro (3.0.8) and in the menu bar menu ignore System Settings. Let me know if you still have the issue after doing this.

**Comment by matchai** [comment]
Hey Ryan 👋 Thank you for the quick response.
It looks like that fixed it on my end! Thank you for the easy workaround 👍
