### ISSUE TITLE
Resize adjacent windows not working

### ISSUE THREAD

**Issue by maxwellhibbert** [rxhanson/RectanglePro-Community#350]
Is there anything obvious that could get in the way of this working?

**Comment by rxhanson** [comment]
There are two different settings for this: one tied to the "Resize" in the window throw tab of the prefs window, and one on the settings tab of the prefs window for dragging window edges. Which one are you having an issue with?

**Comment by maxwellhibbert** [comment]
I was having issue with both settings on. I decided to completely nuke the app and all settings and then reinstall, now it's working.
