### ISSUE TITLE
Terminal commands for altering footprint don't work

### ISSUE THREAD

**Issue by maxwellhibbert** [rxhanson/RectanglePro-Community#351]
Hi, I'm trying to change the footprint colour but it's not working.

I used this info:
[https://github.com/rxhanson/Rectangle/blob/master/TerminalCommands.md#modify-the-footprint-displayed-for-drag-to-snap-area](https://github.com/rxhanson/Rectangle/blob/master/TerminalCommands.md#modify-the-footprint-displayed-for-drag-to-snap-area)

Restarted app and there's no change.

**Comment by rxhanson** [comment]
As a quick sanity check, did you modify the command for Rectangle Pro by replacing `com.knollsoft.Rectangle` with `com.knollsoft.Hookshot`?

**Comment by maxwellhibbert** [comment]
😄   I did not!    sorry,
