### ISSUE TITLE
Quick and Long Throw front window despite cursor position

### ISSUE THREAD

**Issue by sarvothaman** [rxhanson/RectanglePro-Community#365]
Hi,
Is there a setting or something that changes the throw's working so the front window is "thrown" instead of the window that's under the cursor?

Thanks!

**Comment by rxhanson** [comment]
Here's a terminal command to enable this for window throw and long throw:

```defaults write com.knollsoft.Hookshot throwFrontmost -int 1```

There is no toggle for this for quick throw.
