### ISSUE TITLE
Save custom positions

### ISSUE THREAD

**Issue by xApep** [rxhanson/RectanglePro-Community#37]
Awesome app that for sure!

I was wondering if it possible to save modified positions?

**Comment by rxhanson** [comment]
Thanks! I think you're referring to the Applications layouts/groups?

There's not a quick way to "update" an entire layout at this time, so you could either just save a new group, or you could delete the app from the group and add it again with the plus button on the group:

![image](https://user-images.githubusercontent.com/13651296/157891620-fb1dc152-22f8-4524-8550-dc4b035e1d9c.png)
