### ISSUE TITLE
When moving back and forth from external monitor to laptop display, iterm2 does not retain the size correctly

### ISSUE THREAD

**Issue by i-lina** [rxhanson/RectanglePro-Community#382]
On my M2 MacBook Air, I have a 60-40 split between safari and iterm2 on one of my spaces. When I move between the external display and macboook displays, iterm2 display is not retained correctly. Safari retains its size correctly.

**Comment by i-lina** [comment]
iterm2 height is correct, the width is a few pixels short. If I use my keyboard shortcut to reposition/resize, then iterm2 gets to that size correctly.

**Comment by rxhanson** [comment]
Thanks for reporting. 

By default iTerm2 will only resize in increments of character widths. There might be a setting inside iTerm2 to disable this, but you can change it with the following command.

`defaults write com.googlecode.iterm2 DisableWindowSizeSnap -integer 1`

**Comment by i-lina** [comment]
Thanks! that seems to have fixed it.
