### ISSUE TITLE
Feature Request: Repetition: Cycle Corners / Halves

### ISSUE THREAD

**Issue by rgeorgi** [rxhanson/RectanglePro-Community#383]
I would love there to be a repetition option which would:

- If 1/4 corner:
   - cycle  between TR, BR, BL and TL on same monitor
- If 1/2:
   - cycle between U, D or L, R on same monitor

**Comment by rxhanson** [comment]
This will take a little bit of time to set it up, but here's what you need to do:

![image](https://github.com/rxhanson/RectanglePro-Community/assets/13651296/9ef85873-1fb0-4bd5-9c73-4c675f559c61)

**Comment by rgeorgi** [comment]
Fantastic, thank you!
