### ISSUE TITLE
[Feature Request] Zoom Button Snap Panel.

### ISSUE THREAD

**Issue by bigplayer-ai** [rxhanson/RectanglePro-Community#406]
Hi,

I would like to request a feature that allows the Snap Panel to appear below the zoom button, similar to how Moom does it. Please see the attached image for reference.

![Snap_Panel](https://github.com/rxhanson/RectanglePro-Community/assets/119108387/27de2e04-6ddf-4458-a227-e0692bdf7478)

Thank you,

**Comment by rxhanson** [comment]
Thanks for the feedback. I'll close this and just leave the discussion so there's one place to keep updated.
