### ISSUE TITLE
snap not working with some qt-based apps

### ISSUE THREAD

**Issue by daviehh** [rxhanson/RectanglePro-Community#424]
For some qt-based apps (e.g. the flash card app Anki https://github.com/ankitects/anki), the drag-to-snap does not work, and dragging the window do not show the snap panel. Both drag-to-snap and snap panel works with other apps. The windows can be controlled with Rectangle's menubar commands (e.g. left half, etc), just the snap feature seems non-functional. Thanks!

**Comment by rxhanson** [comment]
Thanks for reporting! 

If you don't mind, try this terminal command then restart Rectangle Pro and see if you still have the issue:

```
defaults write com.knollsoft.Hookshot systemWideMouseDown -int 1
```

**Comment by daviehh** [comment]
Fixed after the `defaults write`, thanks for the quick response!
