### ISSUE TITLE
[Feature Request] Default size for specific apps

### ISSUE THREAD

**Issue by addisonjames** [rxhanson/RectanglePro-Community#430]
Would be great to be able to set a default size/position for individual apps, and then set a keyboard shortcut for this (same keyboard shortcut but different settings for each app).
Thanks! 
PS. Just heard about Charmstone- very cool, gonna try.

**Comment by rxhanson** [comment]
To do this, create an app layout and check the box "Only execute on frontmost app".

![image](https://github.com/rxhanson/RectanglePro-Community/assets/13651296/e1d328f2-1109-4129-9a0e-3a6ccd1c4606)

You can set a global one that will match for any apps not are not in the list.

**Comment by addisonjames** [comment]
Works awesome, thanks!

Only wish is that I could use the same shortcut for "Custom Size" and "App Layouts" - then if there's no app in Layouts, it defaults to the Custom Size.
But I understand how niche that request is 🙃 Assuming not possible

**Comment by addisonjames** [comment]
![CleanShot 2024-01-23 at 18 44 16@2x](https://github.com/rxhanson/RectanglePro-Community/assets/4740129/6aef1908-049d-4d29-877c-7f5760114ca0)
Also- is there a way/formula to convert these pixel values to decimal values so they work on multiple display sizes?

(You previously taught me this here: https://github.com/rxhanson/RectanglePro-Community/issues/278)

**Comment by rxhanson** [comment]
> Only wish is that I could use the same shortcut for "Custom Size" and "App Layouts" - then if there's no app in Layouts, it defaults to the Custom Size.

You can manually add a layout to the end and select "Global" for the app.

> Also- is there a way/formula to convert these pixel values to decimal values so they work on multiple display sizes?

Unfortunately you'd have to manually figure out what the display size is and do the calculation yourself. I do have plans to have a way built into the app that will do it for you, but I don't have a timeframe for when that will be in.

**Comment by addisonjames** [comment]
> You can manually add a layout to the end and select "Global" for the app. I think this is what you're looking for, or maybe I don't quite understand?

Perfect, exactly what I was looking for!

I love this app so much 👏
