### ISSUE TITLE
Touching Left Edge of Screen with Cursor Makes Mail App Gain Focus

### ISSUE THREAD

**Issue by jonathankiefer** [rxhanson/RectanglePro-Community#438]
Any time I touch the left edge of my screen with the cursor, the Mail app gains focus. I didn't configure Rectangle Pro to do this, so I'm having trouble figuring out how to disable it. Any ideas?

**Comment by rxhanson** [comment]
Are you using Stash? That's the only feature that is aware of the cursor touching the edge. You can uncheck it in the Settings window if you're not using it.

**Comment by jonathankiefer** [comment]
I have Stash disabled.

![image](https://github.com/rxhanson/RectanglePro-Community/assets/10038122/b27362ae-ed03-444a-ab6b-2bad1689653e)

**Comment by rxhanson** [comment]
As a quick sanity check, does this happen when Rectangle Pro is not running?

**Comment by rxhanson** [comment]
Thanks for the additional information. Unfortunately, I can't reproduce it. Can you attach the following:
1. Your configuration (export it from the General tab).
2. Any logs that are recorded when your cursor hits the edge of the display and Mail gains focus. (Hold the option key in the menu bar menu and select "View Logging..."

**Comment by alecksjaycubd** [comment]
I'm going to add my issue to this one. Weird things happen when my cursor gets to the left edge of my leftmost monitor. I'm also having an issue with windows jumping around when I click on them. I grabbed a video of the left edge issue while logging:

https://www.dropbox.com/scl/fi/u1rvyl5zcjkr579ftabbo/CleanShot-2024-04-09-at-14.58.54.mp4?rlkey=1cyvzig47jgp701frzfoqggpt&dl=0

[RectangleProConfig.json](https://github.com/rxhanson/RectanglePro-Community/files/14923309/RectangleProConfig.json)

**Comment by alecksjaycubd** [comment]
Just want to confirm that, just like @jonathankiefer said above, it doesn't seem to happen until I use a keyboard command to trigger an App Layout.

**Comment by rxhanson** [comment]
Up for trying out this build to see if it fixes this?
https://rectangleapp.com/pro/downloads/Rectangle%20Pro%203.0.23.dmg

**Comment by alecksjaycubd** [comment]
First glance it seems to have fixed it! I'll let it run for a few days and check back in.

**Comment by jonathankiefer** [comment]
Sorry, I seem to have missed your message from a month ago, but I've returned to mention that the latest release does appear to fix this issue. Thanks!
