### ISSUE TITLE
Increase polling rate when dragging / moving windows using shortcuts

### ISSUE THREAD

**Issue by BGDiegoG** [rxhanson/RectanglePro-Community#444]
Rectangle pro has become a vital part of my workflow, primarily resize key bind and move window keybind. I have noticed that when dragging the windows using macOS native method (grabbing the top of the window) the refresh rate of the window moving is very smooth. While when using the keybind on rectanglepro it stutters as in if it was doing it limited to 60hz mode. I notice this more in my high refresh rate screens. 

Is this a macOS limitation?

**Comment by rxhanson** [comment]
Unfortunately, it is a limitation of what's available to a 3rd party developer (the accessibility API). If at some point Apple releases an API outside of the accessibility API, I'll switch it over.

**Comment by BGDiegoG** [comment]
I understand, thank you for confirming this!
