### ISSUE TITLE
Can't activate Todo Mode

### ISSUE THREAD

**Issue by rjmk** [rxhanson/RectanglePro-Community#465]
- [x] This is a new bug that hasn't been documented in a closed issue or in the Readme.

macOS version: 14.2.1
Rectangle version: 3.0.19

I tried running `defaults write com.knollsoft.Rectangle todo -int 1`, and restarting Rectangle. I can't find "Use X as Todo App"

**Comment by rxhanson** [comment]
For Rectangle Pro (v3.0.19), todo mode is referred to as pin mode in the UI. 

For terminal commands, on Rectangle Pro, you'll want to replace com.knollsoft.Rectangle with com.knollsoft.Hookshot (the bundleId for Rectangle Pro is from when it was called Hookshot). The terminal commands are the same, for the most part, so 
`defaults write com.knollsoft.Hookshot todo -int 1` should work if you are avoiding the UI.

**Comment by rjmk** [comment]
Awesome that works great! Thank you
