### ISSUE TITLE
 [Feature Request] Support for multiple spaces in 'App Layout'

### ISSUE THREAD

**Issue by patrickdobler** [rxhanson/RectanglePro-Community#474]
I have 4 monitors, each with 2 spaces. In the applayout I can choose a "display" where the app belongs. It shows me 8 different displays, but display 5-8 is the main display again. I would like to see a distinction between spaces and displays to send the applications to the correct space/display when I run the shortcut of a layout.

I currently have a workaround with yabai/skhdrc, but I think it would be helpful to have this option.

**Comment by rxhanson** [comment]
Thanks for reporting.

>  It shows me 8 different displays, but display 5-8 is the main display again.

Do you have anything unique about your displays or how they are connected? This is the first I've heard of this bug.

> I would like to see a distinction between spaces and displays to send the applications to the correct space/display when I run the shortcut of a layout.

There is no publicly supported way in macOS to send a window/app to a specific space, unfortunately.

**Comment by patrickdobler** [comment]
Thank you for your reply

> There is no publicly supported way in macOS to send a window/app to a specific space, unfortunately.

I see, that's why I haven't found any other solution. At the moment I'm using skhd shortcut to trigger yabai and send the app's to their correct space and then trigger my app layout from rectangle pro, all within a shortcut.

> Do you have anything unique about your displays or how they are connected? This is the first I've heard of this bug.

I don't think there's anything special:

Display1 + 2: DisplayPort/Thunderbolt direct to Macbook
Display3: DisplayPort to docking station to Macbook
Display4: HDMI/HDMI direct to Macbook
Macbook: lid closed

This is how my displays are arranged

![image](https://github.com/rxhanson/RectanglePro-Community/assets/16536946/d1ca42d6-8610-4e3a-9950-5cf2c887a57d)

![image](https://github.com/rxhanson/RectanglePro-Community/assets/16536946/0d6f39c4-adbd-484f-a9e0-aeb52547c8e6)

**Comment by rxhanson** [comment]
Note that the number of displays in this scenario is arbitrary. This is because you might have a scenario where you have configured a window for say, display 4, but you might open up and edit your configuration at a time when display 4 is not available. Although the app is aware that display 4 is not connected, you should still have the option to select display 4 for a time when it will be connected.

**Comment by patrickdobler** [comment]
Thanks for the clarification. I close the feature request as 1. not officially possible due to MacOS limitation and 2. configuration specific and not a problem by definition.
