### ISSUE TITLE
Window throw to first/last third bug

### ISSUE THREAD

**Issue by reinhouthooft** [rxhanson/RectanglePro-Community#483]
When throwing window to first or last third, when the window has already been thrown to the first or last third position respectively,  re-throwing results in the wrong position (cycles through 1st, 2nd and 3rd third).

**Comment by rxhanson** [comment]
Thanks for reporting. I'll fix this in the next release.

**Comment by rxhanson** [comment]
This should now be fixed in v3.0.22. (https://rectangleapp.com/pro/versions)

**Comment by reinhouthooft** [comment]
Fixed, thanks!
