### ISSUE TITLE
Windows are spontaneously unstashing

### ISSUE THREAD

**Issue by pjv** [rxhanson/RectanglePro-Community#487]
This is something new, I believe. I’m only noticing this since the latest update.

<img width="262" alt="SCR-20240406-fkjh" src="https://github.com/rxhanson/RectanglePro-Community/assets/327716/2395d111-dd61-4164-88d3-489080595c17">

I have my stash settings like so:

<img width="435" alt="SCR-20240406-fkbw" src="https://github.com/rxhanson/RectanglePro-Community/assets/327716/9a1a10ea-7b5d-4a23-bc55-45b200bc0790">

And yet, anything that happens which brings an app with a stashed window to the front is causing the stashed window to unstash.

So, for example, if I were to click the icon of a stashed app in the dock, then the window will unstash. More problematically though, if I switch into a space where a stashed window is the only app running on that space so macos automatically brings that app to front, then again the window unstashes. I’m pretty sure this behavior is new and it is definitely an annoyance.

**Comment by rxhanson** [comment]
Thanks for the feedback. Try v3.0.22. https://rectangleapp.com/pro/versions

**Comment by pjv** [comment]
Fixed. Thanks!
