### ISSUE TITLE
Mousewheel-button as Window Throw-modifier traps cursor

### ISSUE THREAD

**Issue by beatschubser** [rxhanson/RectanglePro-Community#502]
I am using the mouse wheel key ("mouse button 3") as the modifier for Window Throw, since this button is the only option for me. 

The throwing-gestures are working fine, but when I click the button without moving the mouse to e.g. close a tab, very often the mouse cursor gets trapped for some time. It also prevents the click from being registered, rendering the mouse button useless for everything but Window Throw.

I tried ramping up "Min. Dist. to Appear", but that doesn't help.

![Bildschirmfoto 2024-05-07 um 14 45 50](https://github.com/rxhanson/RectanglePro-Community/assets/9355283/0dae8562-c448-4e19-aaa3-ed9642e12e38)

In the video the mouse gets trapped three times, the jiggling is me trying to move the mouse away from the window.

https://github.com/rxhanson/RectanglePro-Community/assets/9355283/0fd55d85-21a0-440b-9b11-bba9d2349c1d

OS: macOS 14.4.1
Rectangle Pro Version: v3.0.24
Mouse: Logitech G603

Hope this will be fixed soon.

Cheers

**Comment by rxhanson** [comment]
Thanks for reporting. I'm getting ready to push out a new release and will slate this one for the following release.

**Comment by rxhanson** [comment]
This was broken by macOS, and in my testing it also happens when using my app, Middle, to execute the middle click but not on my mouse with a physical button. It could be that your Logitech mouse is executing the middle click at the same layer as my app, via Logi Options?

**Comment by beatschubser** [comment]
Not sure what you mean by layer, but I am using the mouse without any special drivers like Logi options. It's plug & play with the dongle. I also tested the behaviour via Bluetooh since the mouse can do both, and it's the same.

**Comment by rxhanson** [comment]
Good to know. I'll take a look before I push out the next release, and if it's a quick fix then I'll include it.

**Comment by rxhanson** [comment]
At one point I was able to reproduce this, as mentioned, with my middle click app, Middle, but that is no longer the case. Not being able to reproduce this makes fixing it rather difficult. I wonder if there was some sort of glitch in the macOS event stream that worked itself out. I'm constantly restarting Rectangle Pro as I work on it, so perhaps that has something to do with the issue going away.

**Comment by beatschubser** [comment]
Not what I was hoping to hear.. Window Throw is one of the reasons I bought the Pro-version to be honest.

I just also noticed that the menu bar, which I have set to be hidden unless mouse over, stops working as soon as the issue occurs the first time, and also after the mouse pointer is "free" again. I then have to kill the RectanglePro process and perform another middle click to make the menu bar work again with mouse over.

Another thing I noticed is that I can free the mouse by performing a Window Throw action. Just clicking the middle button without throwing (or any other button) doesn't work.

**Comment by rxhanson** [comment]
I'm confident that we can get to the bottom of this, but there is delicate timing involved and it might take a number of iterations to get there. I'll post a beta build soon with some adjustments.

**Comment by beatschubser** [comment]
Ok, great. If you need me to test anything like a version with extended logging let me know, happy to help.

**Comment by rxhanson** [comment]
Ok, I'm _pretty_ sure that I have a solution, so I went ahead and just rolled out an official release with it. v3.0.26.

https://rectangleapp.com/pro/versions

Let me know how it goes.

**Comment by beatschubser** [comment]
Thank you so much for the fix! Tested a couple of hours now without any issues 🥳
