### ISSUE TITLE
What is the function of the Trackpad configuration in Window Throw?

### ISSUE THREAD

**Issue by aedenbraddock** [rxhanson/RectanglePro-Community#534]
I checked the video you provided below but I'm having an issue getting the trackpad gesture to trigger at all. I've tried all three rest settings and it doesn't trigger when I remove the correct number of fingers. Is there a setting or configuration somewhere on my Macbook that I can look at to find some sort of conflict or issue? 

### Discussed in https://github.com/rxhanson/RectanglePro-Community/discussions/263

<div type='discussions-op-text'>

<sup>Originally posted by **l-qing** April 24, 2023</sup>
Rectangle Pro has very powerful features, which I really like.
But there is one feature that I haven't figured out yet, and I don't know how to use it.

I cannot find the difference between setting it to "-" and "Rest 3 Touches, Remove All Except 1".

After pressing the modifier key, the only effect I noticed was that moving on the trackpad worked, but none of the other keys seemed to have any special functions.

![Shot 2023 04 24 at 20 49 21](https://user-images.githubusercontent.com/9499086/234000964-eb437685-0ba6-4483-80a9-3cb3a84cae4e.png)

Do we have any documentation to see a detailed description of your software? I couldn't find a detailed video on YouTube or official documentation.</div>

**Comment by rxhanson** [comment]
Are you referring to this video? https://www.youtube.com/watch?v=Vo09H-ln7BQ

I recommend slowing it down a little at ~40s in if you haven't watched it.

If you have the min dist to appear set to 0, then the reticle will appear as soon as you remove two of the three touches on the trackpad.

If you still can't get it to work, then you could try removing the Accessibility permission for Rectangle Pro:

1. Quit Rectangle Pro
2. Execute this Terminal command: 
tccutil reset All com.knollsoft.Hookshot
3. Launch Rectangle Pro and give it accessibility permissions again.

Let me know how it goes.

**Comment by aedenbraddock** [comment]
Ah thank you! Setting the minimum distance to 0 helped.

I’m curious though, yesterday when I was messing with the gesture, I did
have my laptop hooked to a docking station with multiple monitors and an
external mouse I wasn’t using.

I didn’t think of it until this morning, but would the external mouse have
conflicted with the trackpad while I was testing it and thus caused it to
appear not to work?


Kind Regards,

Aeden B

**Comment by rxhanson** [comment]
An external mouse typically would not have conflicted with the trackpad, but I never rule out anything when troubleshooting. At any rate, glad you've got it working!
