### ISSUE TITLE
Feature request: better gaps management

### ISSUE THREAD

**Issue by MattOrmianek** [rxhanson/RectanglePro-Community#541]
I really love this app, but there's one feature that would be a game changer for me: the ability to set specific gaps on the top, bottom, right, and left. This would make the app so much better to use.

**Comment by rxhanson** [comment]
Right now this isn't in the UI, so you'll have to use the Terminal to configure it.

Here are the commands:
```
defaults write com.knollsoft.Hookshot screenEdgeGapTop -int 10
defaults write com.knollsoft.Hookshot screenEdgeGapBottom -int 10
defaults write com.knollsoft.Hookshot screenEdgeGapRight -int 10
defaults write com.knollsoft.Hookshot screenEdgeGapLeft -int 10
```
Change 10 to whatever value you want. Restart the app after executing.

**Comment by MattOrmianek** [comment]
Thank you so much for that, I truly appreciate it.
