### ISSUE TITLE
Stash-related actions not working when triggered via URL

### ISSUE THREAD

**Issue by yakirlog** [rxhanson/RectanglePro-Community#550]
# Stash-related actions not working when triggered via URL

## Description
I've encountered an issue where stash-related actions are not functioning when triggered via URL, although they work correctly when using keyboard shortcuts. Other actions are working fine via URL.

## Steps to Reproduce
1. Attempt to trigger stash actions using the following URLs:
   ```
   open -g "rectangle-pro://execute-action?name=stash-down"
   open -g "rectangle-pro://execute-action?name=unstash"
   open -g "rectangle-pro://execute-action?name=toggle-stashed"
   ```
2. Observe that these actions do not perform the expected window management operations.

## Expected Behavior
The stash-related actions should perform their respective window management operations when triggered via URL, just as they do when activated by keyboard shortcuts.

## Actual Behavior
The stash-related actions do not perform any visible operations when triggered via URL.

## Working Examples
For comparison, the following non-stash actions work correctly via URL:
```
open -g "rectangle-pro://execute-action?name=reflow-pin"
open -g "rectangle-pro://execute-action?name=top-left"
```

## Environment
- macOS version: Sonoma v14.5
- Rectangle Pro version: v3.0.30 (171)

## Additional Information
- This issue specifically affects stash-related actions.
- The same actions work correctly when triggered by their assigned keyboard shortcuts.
- Other non-stash actions are functioning as expected via URL.

**Comment by rxhanson** [comment]
Thanks! I just put in a fix and it'll go out in the next release.

**Comment by yakirlog** [comment]
Update: It's working for me now on v3.0.35, thanks Ryan!
