### ISSUE TITLE
Multiple Shortcuts for an Action

### ISSUE THREAD

**Issue by samuelvanderwaal** [rxhanson/RectanglePro-Community#558]
Is it possible to map multiple shortcuts to a single action? I want one shortcut that works on the default Macbook keyboard and a different one for my external keyboard when I have my Macbook connected to an external display and keyboard.

**Comment by rxhanson** [comment]
You can recreate an action using the "Custom Size & Position" tab in the Settings window. Use values less than 1 for sizes relative to the display size. Here's an example of recreating left half (among a few others):

![image](https://github.com/user-attachments/assets/d0301a0d-f442-4b01-af97-ff1cb8478630)

**Comment by samuelvanderwaal** [comment]
Exactly what I need, thank you!
