### ISSUE TITLE
Weird overlay appears arbitrarily on the edge of the primary display

### ISSUE THREAD

**Issue by curldivergence** [rxhanson/RectanglePro-Community#562]
Hi,

Not sure how to describe this problem more concisely, so here are the screenshots:

<img width="267" alt="Screenshot 2024-09-19 at 11 30 53" src="https://github.com/user-attachments/assets/05da2758-4317-42c4-ade5-c2fd8f7eef04">
<img width="405" alt="Screenshot 2024-09-19 at 11 29 32" src="https://github.com/user-attachments/assets/1c84b206-0ec1-4fe7-94ad-8f1408651d6e">
<img width="794" alt="Screenshot 2024-09-19 at 11 27 57" src="https://github.com/user-attachments/assets/5c051da1-583b-415a-b882-e7d9bd8d0626">

I use a Macbook with one external monitor, and this blue overlay/strip appears sporadically (so far haven't understood what triggers it) on the edge of the primary (built-in) display (left display on the screenshots). It is always on top of all windows, it cannot be interacted with, and the only way to make it disappear that I've found is to close and reopen Rectangle Pro (the screenshots are made on the latest version, `3.0.35 (176)`).

Please let me know if you need any other info :)

Thanks!

**Comment by rxhanson** [comment]
This blue strip is the color tabs functionality for the Stash feature. You can disable Stash or uncheck the box for color tabs if it's not something you want to use. 

If it's appearing sporadically and it's not clear what's going on, then perhaps I've got a bug in the Stash feature where windows are being misinterpreted as stashed.

**Comment by curldivergence** [comment]
Got it, thanks a lot for explaining it!
I've just checked and I have had Stash feature disabled in Settings:
<img width="416" alt="Screenshot 2024-09-19 at 18 52 36" src="https://github.com/user-attachments/assets/02592339-7781-4a08-9e5e-eb1852084bbc">
So as I understand, this is unexpected behavior, even though the Color Tabs checkbox is on?

**Comment by rxhanson** [comment]
I was thinking that I had fixed this specific bug, but perhaps I missed an edge case. What is the version number you're running?

**Comment by curldivergence** [comment]
3.0.35 (176)

**Comment by rxhanson** [comment]
Thanks! I'll plan a fix for the next release.

**Comment by curldivergence** [comment]
Awesome, thanks a lot!

**Comment by rxhanson** [comment]
I put in a fix for this one a while back, but it looks like I forgot to close it out. Let me know if you hit this one again somehow.
