### ISSUE TITLE
Question about moving windows across multiple displays

### ISSUE THREAD

**Issue by imofean** [rxhanson/RectanglePro-Community#563]
I have two displays with different resolutions: the left one is 1920x1080, and the right one is 2560x1440. As shown in the clip, when a window moves from the left to the right (using right half), it doesn't automatically maximize, but sometimes it does maximize on its own (as seen at the end of the clip). I would like the window to automatically maximize every time it moves from the left to the right. Is there a way to do this?"

https://www.youtube.com/watch?v=8468VGJAN24

**Comment by rxhanson** [comment]
This one's been on my todo list to fix for a while. I'll see what I can do.

**Comment by rxhanson** [comment]
This should have been fixed in a previous release, but I didn't close out this issue. Let me know if you still see this one.
