### ISSUE TITLE
Size & Position Shortcut Randomly only Moves to Next Monitor without Resizing

### ISSUE THREAD

**Issue by chrisspiegl** [rxhanson/RectanglePro-Community#569]
I have the MacBook internal monitor and a 90degree rotated monitor.
I have a Custom Size & Position shortcut set to "move to the next monitor and set the size to 1x1 (aka 100% by 100%).
However, when I execute the shortcut it only moves the browser window to the next monitor (90deg rotated) and does only sometimes do the resizing.

When executing again, it does work correctly on the internal monitor.

I assume that there may be a delay needed between the "move to second monitor" and then resize after that.

I hope this can get fixed 👍.

**Comment by rxhanson** [comment]
Thanks for letting me know.

> I assume that there may be a delay needed between the "move to second monitor" and then resize after that.

Indeed, I think this is the case. This doesn't reproduce for all displays (including mine), which is why I haven't fixed this one yet. It might take a couple of tries to get the timing right, but I'll let you know when I have a release with an adjustment for this.

**Comment by chrisspiegl** [comment]
I am happy to test any beta versions you may have.
I also have been using this script in Hammerspoon for a while, and it seems to work pretty reliable. Not sure if that helps at all 🙈.

```lua
-- Move the Current Window to the next Screen (loops at the end)
function moveWindow.toNextScreen()
  local window = util.getGoodFocusedWindow(true, true)
  if (not window) then return util.flashScreen([[Can't move this window to the next screen.]]) end
  window:moveToScreen(hs.screen.mainScreen():next()):maximize()
end
```

If you want to connect personally, my details are on my profile / website. Then, maybe, I can help figure this out.

**Comment by rxhanson** [comment]
I'm pretty sure that I have a working fix in place that will be out in the next release (hopefully very soon). If for some reason it doesn't end up working, then I'll take you up on some beta testing :)

**Comment by chrisspiegl** [comment]
Dear @rxhanson, thanks for your swift response. I only was able to test right now.

Version: 3.0.37 (178) on macOS 15.1 (24B83)

It works with multiple external travel-friendly monitors. Especially in portrait mode (90- and 270-degree rotation) and with all kinds of apps (Arc, Obsidian, Teams, Music.app).

Wonderful to have this working 😸. I would say it can be closed.

**Tested with:**

- espresso Display (Pro 17" Model)
- UPERFECT O (OLED 4k 15.6" Model)
