### ISSUE TITLE
Pin mode is not an option in right click context menu

### ISSUE THREAD

**Issue by 5HT2** [rxhanson/RectanglePro-Community#574]
| Right click | Settings |
| --- | --- |
| <img width="216" alt="Screenshot 2024-10-14 at 15 24 11" src="https://github.com/user-attachments/assets/536615fd-9fd8-46d3-a56d-181be43327a4"> | <img width="621" alt="Screenshot 2024-10-14 at 15 23 36" src="https://github.com/user-attachments/assets/1975261d-6d09-4892-bd06-ecaaf2c34c0a"> |

**Comment by rxhanson** [comment]
Ah, thanks! Looks like I somehow missed tying this in. I'll slate it for the next release.

**Comment by 5HT2** [comment]
Thank you so much!

**Comment by 5HT2** [comment]
It works perfectly, thank you so much!!
