### ISSUE TITLE
"Drag windows to screen edges to snap" does not work

### ISSUE THREAD

**Issue by doctopus** [rxhanson/RectanglePro-Community#6]
Upgraded from Hookshot to Rectangle Pro 2.1 (101) and I notice the drag windows to screen edges to snap does not work anymore. I am on MacOs Montery 12.1, MacBook Pro 2.9 GHz 6-Core Intel Core i9. 

Initially after the update, when the app name still remained Hookshot.app the issue was there. I uninstalled and reinstalled the rectangle pro to have the app name as rectangle pro, then also the drag to snap does not work. Please help.

**Comment by rxhanson** [comment]
Are there any apps in specific that have this issue, or is it all apps?

To view logging, hold the option key and select View logging. Is there anything in the logs when this happens?

**Comment by doctopus** [comment]
It happens with all apps. The logging does not log anything while dragging windows to screen edge. However I notice that when I click on any app that is minimized in the dock it shows the log as "Unable to obtain the accessibility element with the specified attribute at mouse location". Does this have to do anything with the snapping at edges to not work.

**Comment by itsbrex** [comment]
@doctopus working fine on both my computers. I upgraded from both Rectangle & Hookshot > Rectangle Pro.

 - M1 Macbook Air running macOS 12.1 (21C52)
 - i9 Macbook Pro running macOS 11.6.2 (20G314)

**Comment by rxhanson** [comment]
@doctopus That log message is unrelated to this issue, but it helps knowing that you don't see anything in the logs there. I'll adjust things for the next release, hopefully out the door soon. You can revert back to v2.0 in the meantime, as 2.1 is where I made optimizations that are causing your issue:
https://rectangleapp.com/pro/versions

**Comment by doctopus** [comment]
@rxhanson Thank you. The v2.0 worked perfectly. And also I discovered that Windows throw was not functioning in v2.1 which works perfectly in v2.0. The logs are all populating well in all the events. Hope you understood what the problem might be. Will wait for it to be fixed in next version. Thank you.

**Comment by doctopus** [comment]
Update: V2.1.1 solves the issue. 

However in this version, dragging window to the lower left and lower right corners does not position the window in the assigned area, instead places the window below the display area only showing part of the window within the viewable area.

**Comment by rxhanson** [comment]
I can’t reproduce that and nothing changed with window placement for this release. Any chance you could gather logs or do a screen recording?

Thanks for testing things out so quickly!

**Comment by doctopus** [comment]
It does not work when dragging windows to the lower side of the screen. I am not sure if this is new in 2.1.1 or it was there since 2.0. I was using this when it was Hookshot. The times when it does not work, the log shows "Unable to obtain window position" Here is a screen recording. https://cln.sh/Y55891

**Comment by JosephTLyons** [comment]
This happens to me too... The action of dragging windows to the edge to snap in Rectangle Pro seems to oscillate between working and not working at random times.
