### ISSUE TITLE
Applying layout only beeps with no window positioning

### ISSUE THREAD

**Issue by dskuza** [rxhanson/RectanglePro-Community#607]
Recently, and I'm not sure why, I can't apply layouts. The system beeps (like Terminal) and no window positions are applied. This is either by hotkey, or another trigger such as when a display is connected. I've tried replacing the shortcut that applies a layout with a different shortcut, and the same issue occurs. I'm unsure what additional details I should provide, but I'm happy to provide any details that may help debug the issue.

**Comment by rxhanson** [comment]
The beep usually means that Rectangle Pro is unable to obtain the window to position or place it in the desired location.

A typical scenario that can lead to this is if your layout is using absolute positions (values > 1) and you have moved the location of your external display in macOS System Settings, as Rectangle Pro does not automatically adjust layouts when this is changed.

The logs should tell us where the problem is. In the menu bar menu, hold the option key and select View Logging, then try applying your layout.

**Comment by dskuza** [comment]
Thanks for the quick reply! Here's what I get after applying the shortcut:

```
2024-12-11T10:15:25-06:00: Nil calculation result
2024-12-11T10:15:25-06:00: Nil calculation result
2024-12-11T10:15:25-06:00: Nil calculation result
2024-12-11T10:15:25-06:00: Nil calculation result
```

**Comment by rxhanson** [comment]
Would you mind sending your config as well? You can export it from the general tab of the settings window.

**Comment by rxhanson** [comment]
Thanks! Still the most likely scenario that would lead to this is if you have moved your display in System Settings without updating the app layout. Only your first app layout looks to be on a display that's not the main one, though, so I would expect that your second app layout would still work in this case. 

I'll add more logging for the next release so it's more clear what happens in this scenario.

If you create a new app layout, does that work fine?

**Comment by dskuza** [comment]
Yep! I just changed my monitor set up, and it seems to work well. I'll go ahead and close this issue.

I understand that there's a way of setting windows on certain displays, but is there a way of setting windows to be on certain _desktops_ on certain displays as well?

**Comment by rxhanson** [comment]
Great! I do have plans to fix the behavior so it will automatically adjust when displays are moved, if possible.

> I understand that there's a way of setting windows on certain displays, but is there a way of setting windows to be on certain desktops on certain displays as well?

Unfortunately not at this time. Apple doesn't provide a way for 3rd party developers to do this. Maybe someday!
