### ISSUE TITLE
[Bug] Window menu appears when highlighting code in Xcode

### ISSUE THREAD

**Issue by albertbori** [rxhanson/RectanglePro-Community#615]
**Steps to Reproduce**

1. Start Rectangle Pro
2. Open a code file in Xcode
3. Click and drag up or down to highlight text

**Expected Results**

Rectangle Pro menu should not be visible

**Actual Result**

Rectangle Pro menu appears

**Video**

https://github.com/user-attachments/assets/fefc6069-742d-42c1-952a-ed6963d26399

**Comment by rxhanson** [comment]
Thanks for reporting, and with a video. I can't reproduce it - would you mind also sending the logs? Hold the option key in the menu bar menu and select View Logging.

**Comment by albertbori** [comment]
No problem! Here's the requested info:

**New Video With Logs**

https://github.com/user-attachments/assets/661c4c3b-b8da-4300-85e5-1cf643ea31f1

**Displays**

* Macbook Pro - M1 Pro 14" Display
* Dell 27"
* Viotek 49" Ultra-wide

![image](https://github.com/user-attachments/assets/8dcbb14e-7d4b-4d52-821b-cbc8813270e3)

**Comment by albertbori** [comment]
Computer Info:
* Apple M1 Pro
* 32 GB Ram
* macOS Sonoma 14.7.1 (23H222)

**Comment by rxhanson** [comment]
Is there anything else unusual about your setup? Any Xcode plugins?

**Comment by albertbori** [comment]
Good catch! I have "GitHub Copilot for Xcode" (v0.29.0) installed. After some testing, I found that disabling this extension makes the issue go away. I will submit the issue to them. Thanks!

![image](https://github.com/user-attachments/assets/0d60464b-5394-4ffd-88e0-9dff4173009c)

**Comment by albertbori** [comment]
Cross-posting this [GitHub Copilot issue report](https://github.com/orgs/community/discussions/148080).

**Comment by rxhanson** [comment]
They're probably adding a transparent window that hovers over Xcode, which has allowed moving by dragging. They should be able to disable the move by dragging, but there might be a reason that they have that enabled in the first place. I'll take another look when I get a chance since it might be something I can add a workaround for.
