### ISSUE TITLE
Prevent windows from overlapping with Dock area

### ISSUE THREAD

**Issue by sarvo-madhavan** [rxhanson/RectanglePro-Community#624]
Currently, I have MacOS Dock "disabled" by using [Sidebar app](https://sidebarapp.net/). This essentially hides the MacOS Dock using the auto hide and setting a very long delay and replaces it with a custom Dock. When I use window throw (I imagine this happens with keyboard shortcuts as well) the bottom part of the window overlaps where the Dock would be likely because Rectangle Pro thinks (rightly so) the Dock is hidden. 

![CleanShot 2024-12-20 at 11 54 49](https://github.com/user-attachments/assets/3268061b-97ad-4dd9-9ead-8ba93c6eed90)

Is there a way to instruct Rectangle to "wall off" x number of pixels on the edge of the screen and to never fill windows there? or perhaps there is another workaround that would work here?

**Comment by rxhanson** [comment]
I have plans to make this configurable in the UI at some point, but here is a terminal command that will add this screen edge gap:

```
defaults write com.knollsoft.Hookshot screenEdgeGapBottom -int 50
```

You'll want to adjust the value there as desired.

Restart the app after running that.
