### ISSUE TITLE
Unhide windows that are hidden in the dock when restoring an application layout

### ISSUE THREAD

**Issue by rxhanson** [rxhanson/RectanglePro-Community#72]
Unhide windows that are hidden in the dock when restoring an application layout? 

I have a layout set to launch all applications if they aren't already open. However, if I hide/minimize one of the windows of this group and re-issue the layout shortcut, it doesn't unhide the window to its proper location. Perhaps this can be a setting?

(Extracted from https://github.com/rxhanson/RectanglePro-Community/issues/46)

**Comment by piechologist** [comment]
Fantastic, I just discovered this feature in Rectangle Pro v2.5. Exactly what I was looking for!
Thank you so much for continually improving this app.

**Comment by rxhanson** [comment]
Thanks for the quick feedback! Note that this currently only works if _all_ of the windows of the app are minimized.
