### ISSUE TITLE
Reflow ToDo and Reflow Pin conflict

### ISSUE THREAD

**Issue by ArcticStag** [rxhanson/RectanglePro-Community#74]
Hi There,

I think this bug came about when I upgraded from Rectangle to Rectangle Pro, I merged over my config and now I have a Reflow ToDo and Reflow Pin, I note that from everything I can see there should not be a Reflow ToDo in Rectangle Pro only the Reflow Pin.

This means that the Reflow shortcut does not work. I think this is because the shortcut is being captured by Reflow ToDo and doing nothing. 

Screenshot Below

![Reflow ToDo Top - Reflow Pin Bottom](https://user-images.githubusercontent.com/60569006/176792954-bde571aa-567b-4028-a1ed-f2754c14646f.png)

**Comment by rxhanson** [comment]
Thanks for reporting! I'll put a fix in for the next release.

**Comment by rxhanson** [comment]
I put a fix in for this a while back but never closed this out. Feel free to reopen if anyone still has an issue here.
