### ISSUE TITLE
Pin Mode does not go all the way to edge of screen when enabled

### ISSUE THREAD

**Issue by ArcticStag** [rxhanson/RectanglePro-Community#77]
When I activate Pin Mode the pinned item sits the exact distance off the left side as the pinned application width.

Below are two screenshots of this issue

**Pin Mode Active with Pinned Item Sublime Text**
![Screen Shot 2022-07-08 at 15 14 36](https://user-images.githubusercontent.com/60569006/177922353-ad2d2230-f733-4bbb-8cef-743d07dba0e6.png)

**Pin Mode deactivated with Pinned Item Sublime text after reflow**
![Screen Shot 2022-07-08 at 15 14 54](https://user-images.githubusercontent.com/60569006/177922349-eb37a3cd-3917-4847-b6eb-5c1de64a1a68.png)

**Pin Mode deactivated with notes open over the pinned item Sublime Text**
![Screen Shot 2022-07-08 at 15 15 30](https://user-images.githubusercontent.com/60569006/177922337-d2d62eb1-29d1-4f00-aca3-ec65b28a94ca.png)

**Comment by rxhanson** [comment]
Thanks for reporting! I'll queue this up for the next release.

**Comment by ArcticStag** [comment]
Hey @rxhanson,

Just wondering if there is any update on this one?

Thank you :)

**Comment by rxhanson** [comment]
Hey thanks for checking in. I did make some changes for this in the last release and forgot to post back here (sorry). I take it you are still having this issue?

**Comment by ArcticStag** [comment]
Yea, Still having this issue. I just checked for updates confirming I am currently on Rectangle Pro 2.4.7 and is the newest version available.

Thanks!

**Comment by ArcticStag** [comment]
Hey @rxhanson 

Any update on this one?

**Comment by rxhanson** [comment]
I'm currently working on the next Pro release and it's on my list.

**Comment by rxhanson** [comment]
Sorry for the delay - please try v2.5.1, where this should now be fixed. You can update within the app or at https://rectangleapp.com/pro

**Comment by ArcticStag** [comment]
The update resolved the issue. Thank you very much. Love your product
