### ISSUE TITLE
Unable to set custom keyboard shortcut

### ISSUE THREAD

**Issue by doctopus** [rxhanson/RectanglePro-Community#9]
Unable to set custom shortcut control+option for Move option under Window Throw. 

It says "This setting would conflict with what you have set for  Next Display". While the Next Display is the default shortcut different from what I want to set for the Move. I cleared the shortcut for Next Display, still it keeps prompting the same. While pressing the shortcut that I want to set, the log says Nil calculation result.

Tested in both Rectangle Pro 2.0 and 2.1. The control+option conflicts with Next Display and Restore in these versions respectively. I am on MacOs Montery 12.1, MacBook Pro 2.9 GHz 6-Core Intel Core i9.

**Comment by doctopus** [comment]
Update: I noticed these conflicts are not from the keyboard shortcuts menu, rather are from the QuickThrow shortcuts even when Quickthrow is disabled. But this is alright. The issue may be closed.

**Comment by doctopus** [comment]
Update: Solved. v2.1.1 addresses the issue. Disabling Quickthorow does not conflict new shortcut assignment with its shortcuts.

**Comment by rxhanson** [comment]
Great, thanks for the quick test.
