### ISSUE TITLE
Feature request: set size by percent, not just pixels

### ISSUE THREAD

**Issue by peterbourgon** [rxhanson/RectanglePro-Community#97]
I'd like for the e.g. "center" shortcut to size the window as 80% tall and 50% wide, relative to my monitor size. Right now there's no way to do that in a way that works across different screen sizes (external monitors).

**Comment by rxhanson** [comment]
To do this, just use values less than 1. They can be decimal or fraction.

<img width="894" alt="Screen Shot 2022-08-29 at 9 16 45 AM" src="https://user-images.githubusercontent.com/13651296/187211965-c4333c0c-0592-4a33-9028-7d77a835c222.png">

I have plans to make this more apparent in the app, at the moment it's something you only figure out if you click on the info button and read the info.

**Comment by peterbourgon** [comment]
Oh! Great! Thanks!
